name: Add Label and Reviewer for master branch

on:
  pull_request:
    branches:
      - master

jobs:
  add_label_and_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: '.github/labeler-master.yml'
      - uses: kentaro-m/auto-assign-action@v1.1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: '.github/auto_assign.yml'
