name: Create Release Branch and Pull Request

on: [ workflow_dispatch ]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set current datetime as env variable
        id: datetime
        run: echo "::set-env name=datetime::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release/${{ steps.datetime.outputs.datetime }}
          git push origin release/${{ steps.datetime.outputs.datetime }}
      - name: create diff
        run: echo ::set-env name=BODY::$(git log origin/master..origin/release/${{ steps.datetime.outputs.datetime }} --merges --first-parent --reverse --pretty=format:"* %b \n")
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "release$/{{ steps.datetime.outputs.datetime }}"
          destination_branch: "master"
          pr_title: release/${{ steps.datetime.outputs.datetime }} # Title of pull request
          pr_body: "${{ env.BODY }}"
