name: Create Release Branch and Pull Request

on: [ workflow_dispatch ]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release
          git push origin release
      - name: create diff
        run: echo ::set-env name=BODY::$(git log origin/master..origin/release --merges --first-parent --reverse --pretty=format:"* %b \n")
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "release"
          destination_branch: "master"
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: "${{ env.BODY }}"
