name: Add Label and Reviewer for subtask branch

on:
  pull_request:
    branches-ignore:
      - develop
      - master

jobs:
  add_label_and_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: '.github/labeler/subtask.yml'
